US001 - View Job Roles Backend
Binary-Butterflies/kainos-job-api pull request #1
Opened 2024-12-18 11:33 UTC by dylanmckk

2024-12-20 09:56 UTC, MatthewJKainos commented on src/main/java/org/example/services/JobRoleService.java
> +        LOGGER.info("Mapping JobRole list to JobRoleResponse list");
Should this be a debug message?

2024-12-20 09:57 UTC, MatthewJKainos commented on src/main/resources/db/migration/V1__create_job_role_tables.sql
> +    capabilityId INT,
Should these be `NOT NULL`?

2024-12-20 09:58 UTC, MatthewJKainos commented on src/main/resources/db/migration/V1__create_job_role_tables.sql
> +    bandId INT,
Should these be `NOT NULL`?

2024-12-20 10:03 UTC, MatthewJKainos requested changes
Please see added comments

2024-12-20 10:11 UTC, MatthewJKainos approved these changes
👍

2024-12-20 10:24 UTC, MatthewJKainos requested changes
Sorry, issue came up in the front end

2024-12-20 10:24 UTC, MatthewJKainos commented on src/main/java/org/example/models/JobRoleResponse.java
> +    private final int jobRoleId;
We also need to return the band name and capability name

2024-12-20 10:24 UTC, MatthewJKainos commented on src/main/java/org/example/models/JobRole.java
> +    private final Date closingDate;
We'll also need a band name and capability name here

2024-12-20 10:24 UTC, MatthewJKainos commented on src/main/java/org/example/daos/JobRoleDao.java
> +                    "SELECT * FROM job_roles");
I'd recommend using a join here to get the band and capability names

2024-12-20 10:50 UTC, lukemKainos requested changes

2024-12-20 10:50 UTC, lukemKainos commented on src/main/java/org/example/controllers/JobRoleController.java
> +            LOGGER.error("Error getting job roles {}", e.toString());
why do we convert to a string here?

2024-12-20 10:50 UTC, lukemKainos commented on src/test/java/org/example/controllers/JobRoleControllerTest.java
> +        LOGGER.info("Initialised Unit Test for getAllJobRoles_ReturnsJobRoles_ReturnTwoHundred");
like the thought process but we dont need loggers inside our tests, tests should be self documenting

2024-12-20 11:48 UTC, dylanmckk commented on src/main/java/org/example/controllers/JobRoleController.java
> +            LOGGER.error("Error getting job roles {}", e.toString());
If I were to do e.message(), it wouldn't include the name of the error class e.g. InvalidException

2025-01-07 10:48 UTC, lukemKainos approved these changes

2025-01-07 10:48 UTC, MatthewJKainos approved these changes

2025-01-07 10:56 UTC, merged